### ISSUE TITLE
Not working with latest version of Chart.js

### ISSUE THREAD

**Issue by tanmaybhatt** [tomsouthall/Chart.HorizontalBar.js#23]
Chart.HorizontalBar.js is working with the version of Chart.js you linked in the sample HTML. 
But as soon as I replace the link with local Chart.js file, it says Chart.Type is undefined
But then I realized that your Chart.js file is version 1.0.2 and the version I have is 2.1.3 

![file](https://cloud.githubusercontent.com/assets/16023331/15427605/f3027832-1eb3-11e6-91b2-3b3839b53e79.PNG)

The above image is the error in your sample HTML file itself.

**Comment by amir-infsoft** [comment]
I have the same problem. Any info if you will update so it works with chart.js v2 ?

**Comment by simonadomnisoru** [comment]
+1

**Comment by tanmaybhatt** [comment]
New version of Chart.js itself has a new option for horizontal bars . Hence, I will close this issue
